---
- name: Create user and home directory
  user:
    home: "{{ project.root }}"
    name: "{{ project.user }}"
    groups: "{{ project.group }}"
    state: present

- name: Change user home directory permissions
  file:
    state: directory
    owner: "{{ project.user }}"
    group: "{{ project.group }}"
    path: "{{ project.root }}"

- name: Ensure there is a logs directory
  file:
    state: directory
    owner: "{{ project.user }}"
    group: "{{ project.group }}"
    path: "{{ project.root }}/logs"

- name: Remove Temp Files
  file:
    path: /tmp/greentogo
    state: absent