# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
