# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 23:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                (
                    'page_ptr', models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page'
                    )
                ),
                (
                    'repeat_in_subnav', models.BooleanField(
                        default=False,
                        help_text="If checked, a link to this page will be repeated alongside it's direct children when displaying a sub-navigation for this page.",
                        verbose_name='repeat in sub-navigation'
                    )
                ),
                (
                    'repeated_item_text', models.CharField(
                        blank=True,
                        help_text="e.g. 'Section home' or 'Overview'. If left blank, the page title will be used.",
                        max_length=255,
                        verbose_name='repeated item link text'
                    )
                ),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', ),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                (
                    'page_ptr', models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page'
                    )
                ),
                (
                    'repeat_in_subnav', models.BooleanField(
                        default=False,
                        help_text="If checked, a link to this page will be repeated alongside it's direct children when displaying a sub-navigation for this page.",
                        verbose_name='repeat in sub-navigation'
                    )
                ),
                (
                    'repeated_item_text', models.CharField(
                        blank=True,
                        help_text="e.g. 'Section home' or 'Overview'. If left blank, the page title will be used.",
                        max_length=255,
                        verbose_name='repeated item link text'
                    )
                ),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', ),
        ),
    ]
