# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('_encrypted_password', models.CharField(max_length=100)),
            ], ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
                ('customer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='core.Customer')),
            ], ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('plan', models.CharField(max_length=25)),
                ('started_on', models.DateTimeField()),
                ('expires_on', models.DateTimeField(
                    blank=True, null=True)),
                ('stripe_id', models.CharField(
                    blank=True, max_length=100, null=True, unique=True)),
                ('admin', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='core.Customer')),
            ], ),
        migrations.AddField(
            model_name='customer',
            name='subscriptions',
            field=models.ManyToManyField(to='core.Subscription'), ),
    ]
