# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0001_initial'), ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscriptions',
            field=models.ManyToManyField(to='pinax_stripe.Subscription'), ),
    ]
