# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_id',
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.PositiveIntegerField(help_text='Amount in cents.'),
        ),
    ]
