# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170218_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscriptions',
            field=models.ManyToManyField(to='core.Subscription'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[],
            options={
                'proxy': True,
            },
            bases=('pinax_stripe.subscription', ),
        ),
    ]
