# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('core', '0002_location_locationtag_subscriptionplan'), ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='core.SubscriptionPlan'), ),
    ]
