# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 22:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('core', '0003_auto_20170204_2018'), ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='admin',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='owned_subscriptions',
                to='core.Customer'), ),
        migrations.AlterField(
            model_name='subscription',
            name='expires_on',
            field=models.DateField(
                blank=True, null=True), ),
        migrations.AlterField(
            model_name='subscription',
            name='started_on',
            field=models.DateField(), ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(
                help_text='Code must be capital letters and numbers with no spaces.',
                max_length=25,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator('^[A-Z0-9]+$')
                ]), ),
    ]
