# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0003_auto_20170218_1638'), ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscriptions',
            field=models.ManyToManyField(
                related_name='subscribers', to='core.Subscription'), ),
    ]
