# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0004_auto_20170221_0235'), ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(
                blank=True, max_length=255, null=True), ),
    ]
