# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170311_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=1023)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
