# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-05 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subscription_stripe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
