# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phase',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
