# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 18:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170805_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationStockCount',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.PositiveIntegerField()),
                (
                    'location', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Location'
                    )
                ),
            ],
        ),
    ]
