# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 02:00
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_locationstockcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateCode',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('company_name', models.CharField(max_length=100)),
                (
                    'code', models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=
                                'Code can only contain capitol letters and numbers with no spaces. Must be between 4 and 20 characters.',
                                regex='[A-Z0-9]{4,20}'
                            )
                        ]
                    )
                ),
                ('amount_off', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('redeem_by', models.DateField(default=core.models.one_year_from_now)),
            ],
        ),
        migrations.AlterField(
            model_name='locationstockcount',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='stock_counts',
                to='core.Location'
            ),
        ),
    ]
