# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 23:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_restaurant_phase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='subscriptions',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'pinax_subscription', models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='g2g_subscription',
                        to='pinax_stripe.Subscription'
                    )
                ),
                (
                    'subscribers',
                    models.ManyToManyField(related_name='subscriptions', to='core.Subscriber')
                ),
            ],
        ),
    ]
