# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170403_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='uuid',
        ),
        migrations.RunSQL(
            "ALTER TABLE core_location ADD COLUMN id SERIAL PRIMARY KEY",
            state_operations=[
                migrations.AddField(
                    model_name='location',
                    name='id',
                    field=models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                    preserve_default=False,
                ),
            ]
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default='', max_length=1023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.CharField(default='', max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
