# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 01:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170814_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='corporate_code',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.CorporateCode'
            ),
        ),
    ]
