# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170407_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationtag',
            name='location',
        ),
    ]
