# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170814_1332'),
        ('core', '0011_subscription_corporate_code'),
    ]

    operations = []
