# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 23:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_locationtag_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationtag',
            name='subscription',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='pinax_stripe.Subscription'
            ),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pinax_subscription',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_subscriptions',
                to='pinax_stripe.Subscription'
            ),
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
