# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-22 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_location_admin_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
