# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 18:59
from __future__ import unicode_literals

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180221_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Code can only contain capitol letters and numbers with no spaces. Must be between 4 and 20 characters.', regex='^[A-Z0-9]{4,20}$')])),
                ('value', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('redeem_by', models.DateField(default=core.models.one_year_from_now)),
                ('duration', models.CharField(choices=[('once', 'once'), ('forever', 'forever')], help_text='This describes if the coupon should be applied once, orevery time the subscription is renewed', max_length=100)),
                ('is_percentage', models.BooleanField(default=False)),
            ],
        )
    ]
