# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 21:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0004_plan_metadata'),
        ('core', '0015_subscription_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionInvitation',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('code', models.CharField(max_length=40)),
                (
                    'pinax_subscription', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invitations',
                        to='pinax_stripe.Subscription'
                    )
                ),
            ],
        ),
    ]
