# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180313_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponcode',
            old_name='company_name',
            new_name='coupon_name',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Plan'),
        ),
    ]
