# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-18 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180313_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationStockReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actual_amount', models.PositiveIntegerField()),
                ('estimated_amount', models.PositiveIntegerField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reports', to='core.Location')),
            ],
        ),
    ]
