# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 01:40
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_subscriptioninvitation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('name', models.CharField(max_length=255, unique=True)),
                ('available', models.BooleanField(default=True)),
                ('amount', models.PositiveIntegerField()),
                ('number_of_boxes', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriptioninvitation',
            name='pinax_subscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='locationtag',
            name='subscription',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='core.Subscription'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='SubscriptionInvitation',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='pinax_subscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Plan'
            ),
        ),
    ]
