# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_couponcode_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CouponCode'),
        ),
    ]
