# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-22 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_subscription_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='duration',
            field=models.CharField(choices=[('once', 'once'), ('forever', 'forever')], default='once', help_text='This describes if the coupon should be applied once, or every time the subscription is renewed', max_length=100),
        ),
    ]
