# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-22 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180322_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='plans',
            field=models.ManyToManyField(blank=True, help_text='Selecting no plans to make this coupon available for all plans. ', related_name='coupons', to='core.Plan'),
        ),
    ]
