# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-31 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_couponcode_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='retired',
            field=models.BooleanField(default=False, help_text='Retired locations will not show up in reporting         but their data will remain in history.'),
        ),
    ]
