# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-03 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_location_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
