# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='interval',
            field=models.CharField(default='year', help_text="Should say 'year' or 'month'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='locationstockcount',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='locationstockreport',
            name='actual_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='locationstockreport',
            name='estimated_amount',
            field=models.IntegerField(),
        ),
    ]
