# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20180525_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='admin_location',
            field=models.BooleanField(default=False, help_text='Admin locations are locations where         boxes will be checked in when they are         cleaned.         THERE CAN ONLY BE ONE ADMIN LOCATION!'),
        ),
    ]
