# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-01 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20180525_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='dumping_location',
            field=models.BooleanField(default=False, help_text="dumping_location is a location where         accidental checkout boxes are 'checked in' to.         THERE CAN ONLY BE ONE DUMPING LOCATION!"),
        ),
        migrations.AddField(
            model_name='location',
            name='headquarters',
            field=models.BooleanField(default=False, help_text='Headquarters is a location where         boxes will be moved to when they are         cleaned.         THERE CAN ONLY BE ONE HEADQUARTER LOCATION!'),
        ),
        migrations.AddField(
            model_name='location',
            name='washing_location',
            field=models.BooleanField(default=False, help_text='washing_location is a location where         boxes are moved when they are picked up         from checkin locations.         THERE CAN ONLY BE ONE WASHING LOCATION!'),
        ),
        migrations.AlterField(
            model_name='location',
            name='admin_location',
            field=models.BooleanField(default=False, help_text='Admin locations are locations that         are only supposed to be used for administrative         and backend purposes.'),
        ),
    ]
