# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-04 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20180701_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='notify',
            field=models.BooleanField(default=False, help_text='If checked, an email will be sent any         time a box is checked in or out of this location'),
        ),
        migrations.AddField(
            model_name='location',
            name='notifyEmail',
            field=models.CharField(blank=True, help_text='Email for notify option', max_length=255),
        ),
    ]
