# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-04 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20180703_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='interval',
            field=models.CharField(choices=[('month', 'month'), ('year', 'year')], default='year', help_text="Should say 'year' or 'month'.", max_length=255),
        ),
    ]
