# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-05 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_restaurant_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
