# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-27 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_restaurant_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
