# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-27 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_location_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='phase',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
