# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-29 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_adminsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='highStockEmails',
            field=models.TextField(default='me@greentogo.com', help_text='List of emails separated by commas for who should recieve alerts when stock is high at return stations', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='lowStockEmails',
            field=models.TextField(help_text='List of emails separated by commas for who should recieve alerts when stock is low at restaurants', max_length=1024),
        ),
    ]
