# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-20 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_adminsettings_appvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expoPushToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
