# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-25 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_mobileappratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='minimum_boxes',
            field=models.IntegerField(default=15, help_text='Minimum number of boxes to be kept at this check out         location (please ignore for non-check out locations)'),
        ),
    ]
