# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-01-01 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_location_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='maximum_boxes',
            field=models.IntegerField(default=40),
        ),
    ]
