# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-03 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restaurant_manager',
            field=models.ManyToManyField(to='core.Location'),
        ),
    ]
