# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-03 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_user_restaurant_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
