# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-04 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_reward_redeemed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='restaurant_manager',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
