# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-04 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_location_restaurant_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='preferred_delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
