# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-04 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_location_preferred_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='preferred_delivery_time',
            field=models.CharField(choices=[('ANY', 'Anytime'), ('8AM', '8 am'), ('9AM', '9 am'), ('10AM', '10 am'), ('11AM', '11 am'), ('12PM', '12 pm'), ('1PM', '1 pm'), ('2PM', '2 pm'), ('3PM', '3 pm'), ('4PM', '4 pm'), ('5PM', '5 pm'), ('6PM', '6 pm'), ('7PM', '7 pm'), ('8PM', '8 pm'), ('9PM', '9 pm')], default='ANY', max_length=25),
        ),
    ]
