# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-09-25 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20190715_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='has_boxes',
            field=models.BooleanField(default=True, help_text='If the location uses take out containers or not'),
        ),
        migrations.AddField(
            model_name='location',
            name='has_cups',
            field=models.BooleanField(default=False, help_text='If the location uses take out cups or not'),
        ),
        migrations.AddField(
            model_name='locationtag',
            name='item_type',
            field=models.CharField(choices=[('CUP', 'Cup'), ('BOX', 'Box')], default='BOX', max_length=25),
        ),
    ]
