# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-10-27 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_grouporder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouporder',
            name='expected_checkout',
            field=models.DateField(blank=True),
        ),
    ]
