# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-11-07 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20191027_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='newSubEmails',
            field=models.TextField(default='info@dontwastedurham.com', help_text='List of emails separated by commas for who should recieve alerts about new subscriptions', max_length=1024),
        ),
    ]
