---
project_name: greentogo
apt_upgrade: no
git_tmp_dir: /tmp/greentogo/

lets_encrypt:
  email: clinton@dreisbach.us

project:
  name: "{{ project_name }}"
  user: greentogo
  group: www-data
  mode: live
  root: /opt/{{ project_name }}/
  srcroot: /opt/{{ project_name }}/src/
  maintainer_email: clinton@dreisbach.us
  virtualenv: /opt/{{ project_name }}/env/
  domain: g2g.dreisbach.us
  url: "https://g2g.dreisbach.us"

django:
  root: "{{ project.srcroot }}greentogo/"
  env: staging
  settings: greentogo.settings

repo:
  branch: master
  url: "https://github.com/greentogo/greentogo.git"
