# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('stripe_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('display_price', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateField(auto_now_add=True)),
                ('internal_id', models.UUIDField(
                    default=uuid.uuid4, editable=False, unique=True)),
                ('stripe_id', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='beta_signup.Customer')),
                ('plan', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='beta_signup.Plan')),
            ],
        ),
    ]
