# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_signup', '0002_auto_20161211_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='gifted_to_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gifted_to_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
