# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0004_plan_metadata'),
        ('beta_signup', '0003_auto_20161212_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftSubscription',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('gifted_to_name', models.CharField(
                    blank=True, max_length=255)),
                ('gifted_to_email', models.CharField(
                    blank=True, max_length=255)),
            ], ),
        migrations.RemoveField(
            model_name='subscription',
            name='customer', ),
        migrations.DeleteModel(
            name='Customer', ),
        migrations.DeleteModel(
            name='Subscription', ),
        migrations.AddField(
            model_name='giftsubscription',
            name='stripe_subscription',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to='pinax_stripe.Subscription'), ),
    ]
